### ISSUE TITLE
Random forests example investigation

### ISSUE THREAD

**Issue by briannaburton1** [OlehKSS/IMMAS#53]
Random forest example of usage can be found here.
[Link to resource](https://www.kaggle.com/jeffd23/scikit-learn-ml-from-start-to-finish)

Provide an example of usage for our problem if possible.

**Comment by OlehKSS** [comment]
I was reading the article [An Efficient Approach for Automated Mass Segmentation and Classification in Mammograms](https://github.com/OlehKSS/IMMAS/blob/master/Articles/An%20Efficient%20Approach%20for%20Automated%20Mass%20Segmentation%20and%20Classification%20in%20Mammograms.pdf) and they praise random forest classifier:
*Last and most important, the random forest classifier used in this work improves the classification accuracy significantly. The random forest is selected for classification because of its interesting properties: (1) deal with high dimension feature without feature selection, (2) accommodate many predictor variables, (3) during creating random forests, generalization error using unbiased estimation, and (4) run new data through previously generated forests to generate classifications*

**Comment by doiriel** [comment]
SVM used in 5/8 papers Random forest 3/8.

**SVM** 
A novel computer aided breast mass detection scheme based on morphological enhancement and SLIC superpixel segmentation
Local_Binary_Patterns
False Positive Reduction in Mammographic Mass Detection Using Local Binary Patterns
Automatic Detection of Masses in Mammograms Using Quality Threshold Clustering, Correlogram Function, and SVM
Mass Detection and Classification using Machine Learning Techniques in Digital Mammograms
**Random forests**
An Efficient Approach for Automated Mass Segmentation and Classification in Mammograms
Assessment of a novel mass detection algorithm in mammograms (Rotation forest)
Automated Mass Detection in Mammograms using Cascaded Deep Learning and Random Forests
